export const CONTRIBUTION_SYMBOL =
  (import.meta.env.VITE_CHAINORA_CONTRIBUTION_SYMBOL as string | undefined) || 'tcUSD';

export const DASHBOARD_PUBLIC_POLL_INTERVAL_MS = 6_000;
export const DASHBOARD_JOINED_POLL_INTERVAL_MS = 24_000;
export const DASHBOARD_PUBLIC_SYNC_MIN_GAP_MS = 12_000;
export const DASHBOARD_JOINED_SYNC_MIN_GAP_MS = 45_000;
export const DASHBOARD_PUBLIC_RESUME_SYNC_MIN_GAP_MS = 6_000;
export const DASHBOARD_JOINED_RESUME_SYNC_MIN_GAP_MS = 15_000;
export const DASHBOARD_PUBLIC_GROUP_CACHE_STALE_MS = 8_000;
export const DASHBOARD_JOINED_GROUP_CACHE_STALE_MS = 20_000;
export const DASHBOARD_PUBLIC_EMPTY_RESULT_SYNC_STREAK_THRESHOLD = 1;
export const DASHBOARD_JOINED_EMPTY_RESULT_SYNC_STREAK_THRESHOLD = 2;
export const DASHBOARD_JOINED_MEMBERSHIP_REFRESH_TTL_MS = 60_000;
export const DASHBOARD_SEARCH_DEBOUNCE_MS = 300;

export const REFRESH_INTERVAL_MS = DASHBOARD_PUBLIC_POLL_INTERVAL_MS;
export const JOINED_REFRESH_INTERVAL_MS = DASHBOARD_JOINED_POLL_INTERVAL_MS;
export const JOINED_FILTER_TIMEOUT_MS = 3_500;

export const DASHBOARD_GROUP_CACHE_KEY_PREFIX = 'chainora:dashboard:groups:v1';
export const DASHBOARD_JOINED_POOL_CACHE_KEY_PREFIX = 'chainora:dashboard:joined-pools:v1';
export const DASHBOARD_PREFERRED_MODE_KEY = 'chainora:dashboard:preferred-mode:v1';
export const DASHBOARD_FORCE_SYNC_ONCE_KEY = 'chainora:dashboard:force-sync-once:v1';
