export const REGISTRY_ABI = [
  {
    type: 'function',
    name: 'stablecoin',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'deviceAdapter',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'reputationAdapter',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'stakingAdapter',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
] as const;

export const FACTORY_ABI = [
  {
    type: 'function',
    name: 'poolCount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'poolById',
    stateMutability: 'view',
    inputs: [{ name: 'poolId', type: 'uint256' }],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'createPool',
    stateMutability: 'nonpayable',
    inputs: [
      {
        name: 'config',
        type: 'tuple',
        components: [
          { name: 'contributionAmount', type: 'uint256' },
          { name: 'targetMembers', type: 'uint16' },
          { name: 'periodDuration', type: 'uint32' },
          { name: 'contributionWindow', type: 'uint32' },
          { name: 'auctionWindow', type: 'uint32' },
        ],
      },
    ],
    outputs: [
      { name: 'pool', type: 'address' },
      { name: 'poolId', type: 'uint256' },
    ],
  },
] as const;

export const POOL_ABI = [
  {
    type: 'function',
    name: 'poolStatus',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint8' }],
  },
  {
    type: 'function',
    name: 'currentCycle',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'currentPeriod',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'activeMemberCount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint16' }],
  },
  {
    type: 'function',
    name: 'cycleCompleted',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'members',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address[]' }],
  },
  {
    type: 'function',
    name: 'isMember',
    stateMutability: 'view',
    inputs: [{ name: 'member', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'isActiveMember',
    stateMutability: 'view',
    inputs: [{ name: 'member', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'memberDeposit',
    stateMutability: 'view',
    inputs: [{ name: 'member', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'claimableYield',
    stateMutability: 'view',
    inputs: [{ name: 'member', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'periodInfo',
    stateMutability: 'view',
    inputs: [
      { name: 'cycleId', type: 'uint256' },
      { name: 'periodId', type: 'uint256' },
    ],
    outputs: [
      { name: 'status', type: 'uint8' },
      { name: 'startAt', type: 'uint64' },
      { name: 'contributionDeadline', type: 'uint64' },
      { name: 'auctionDeadline', type: 'uint64' },
      { name: 'recipient', type: 'address' },
      { name: 'bestBidder', type: 'address' },
      { name: 'bestDiscount', type: 'uint256' },
      { name: 'totalContributed', type: 'uint256' },
      { name: 'payoutAmount', type: 'uint256' },
      { name: 'payoutClaimed', type: 'bool' },
      { name: 'reputationSnapshotId', type: 'bytes32' },
    ],
  },
  {
    type: 'function',
    name: 'proposeInvite',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'candidate', type: 'address' }],
    outputs: [{ name: 'proposalId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'voteInvite',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'proposalId', type: 'uint256' },
      { name: 'support', type: 'bool' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'acceptInviteAndLockDeposit',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'proposalId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'contribute',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'submitDiscountBid',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'discount', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'closeAuctionAndSelectRecipient',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'claimPayout',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'claimYield',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'finalizePeriod',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'markDefaultAndPause',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'defaultedMember', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'voteContinueAfterPause',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'support', type: 'bool' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'voteExtendCycle',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'support', type: 'bool' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'archive',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'leaveAfterArchive',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
] as const;

export const ERC20_ABI = [
  {
    type: 'function',
    name: 'approve',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'allowance',
    stateMutability: 'view',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'spender', type: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
] as const;
