export const REGISTRY_ABI = [
  {
    type: 'function',
    name: 'stablecoin',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'deviceAdapter',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'reputationAdapter',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'stakingAdapter',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
] as const;

export const FACTORY_ABI = [
  {
    type: 'event',
    name: 'ChainoraPoolCreated',
    inputs: [
      { indexed: true, name: 'poolId', type: 'uint256' },
      { indexed: true, name: 'pool', type: 'address' },
      { indexed: true, name: 'creator', type: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'function',
    name: 'poolCount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'poolById',
    stateMutability: 'view',
    inputs: [{ name: 'poolId', type: 'uint256' }],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'createPool',
    stateMutability: 'nonpayable',
    inputs: [
      {
        name: 'config',
        type: 'tuple',
        components: [
          { name: 'contributionAmount', type: 'uint256' },
          { name: 'minReputation', type: 'uint256' },
          { name: 'targetMembers', type: 'uint16' },
          { name: 'periodDuration', type: 'uint32' },
          { name: 'contributionWindow', type: 'uint32' },
          { name: 'auctionWindow', type: 'uint32' },
        ],
      },
    ],
    outputs: [
      { name: 'pool', type: 'address' },
      { name: 'poolId', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'createPool',
    stateMutability: 'nonpayable',
    inputs: [
      {
        name: 'config',
        type: 'tuple',
        components: [
          { name: 'contributionAmount', type: 'uint256' },
          { name: 'minReputation', type: 'uint256' },
          { name: 'targetMembers', type: 'uint16' },
          { name: 'periodDuration', type: 'uint32' },
          { name: 'contributionWindow', type: 'uint32' },
          { name: 'auctionWindow', type: 'uint32' },
        ],
      },
      { name: 'publicRecruitment', type: 'bool' },
    ],
    outputs: [
      { name: 'pool', type: 'address' },
      { name: 'poolId', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'recruitingPoolCount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'recruitingPool',
    stateMutability: 'view',
    inputs: [{ name: 'poolId', type: 'uint256' }],
    outputs: [
      {
        type: 'tuple',
        components: [
          { name: 'poolId', type: 'uint256' },
          { name: 'pool', type: 'address' },
          { name: 'creator', type: 'address' },
          { name: 'publicRecruitment', type: 'bool' },
          { name: 'listed', type: 'bool' },
          { name: 'poolStatus', type: 'uint8' },
          { name: 'activeMemberCount', type: 'uint256' },
          { name: 'targetMembers', type: 'uint16' },
          { name: 'contributionAmount', type: 'uint256' },
          { name: 'minReputation', type: 'uint256' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'recruitingPools',
    stateMutability: 'view',
    inputs: [
      { name: 'offset', type: 'uint256' },
      { name: 'limit', type: 'uint256' },
    ],
    outputs: [
      {
        type: 'tuple[]',
        components: [
          { name: 'poolId', type: 'uint256' },
          { name: 'pool', type: 'address' },
          { name: 'creator', type: 'address' },
          { name: 'publicRecruitment', type: 'bool' },
          { name: 'listed', type: 'bool' },
          { name: 'poolStatus', type: 'uint8' },
          { name: 'activeMemberCount', type: 'uint256' },
          { name: 'targetMembers', type: 'uint16' },
          { name: 'contributionAmount', type: 'uint256' },
          { name: 'minReputation', type: 'uint256' },
        ],
      },
    ],
  },
] as const;

export const POOL_ABI = [
  {
    type: 'event',
    name: 'ChainoraInviteProposed',
    inputs: [
      { indexed: true, name: 'proposalId', type: 'uint256' },
      { indexed: true, name: 'candidate', type: 'address' },
      { indexed: true, name: 'proposer', type: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ChainoraInviteVoted',
    inputs: [
      { indexed: true, name: 'proposalId', type: 'uint256' },
      { indexed: true, name: 'voter', type: 'address' },
      { indexed: false, name: 'support', type: 'bool' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ChainoraInviteAccepted',
    inputs: [
      { indexed: true, name: 'proposalId', type: 'uint256' },
      { indexed: true, name: 'member', type: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ChainoraJoinRequestSubmitted',
    inputs: [
      { indexed: true, name: 'requestId', type: 'uint256' },
      { indexed: true, name: 'applicant', type: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ChainoraJoinRequestVoted',
    inputs: [
      { indexed: true, name: 'requestId', type: 'uint256' },
      { indexed: true, name: 'voter', type: 'address' },
      { indexed: false, name: 'support', type: 'bool' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ChainoraJoinRequestAccepted',
    inputs: [
      { indexed: true, name: 'requestId', type: 'uint256' },
      { indexed: true, name: 'member', type: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'function',
    name: 'poolStatus',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint8' }],
  },
  {
    type: 'function',
    name: 'currentCycle',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'currentPeriod',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'activeMemberCount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'cycleCompleted',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'extendVoteState',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      { name: 'open', type: 'bool' },
      { name: 'round', type: 'uint256' },
      { name: 'yesVotes', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'creator',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'publicRecruitment',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'targetMembers',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint16' }],
  },
  {
    type: 'function',
    name: 'minReputation',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'periodDuration',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint32' }],
  },
  {
    type: 'function',
    name: 'contributionWindow',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint32' }],
  },
  {
    type: 'function',
    name: 'auctionWindow',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint32' }],
  },
  {
    type: 'function',
    name: 'members',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address[]' }],
  },
  {
    type: 'function',
    name: 'activeMembers',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address[]' }],
  },
  {
    type: 'function',
    name: 'isMember',
    stateMutability: 'view',
    inputs: [{ name: 'member', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'isActiveMember',
    stateMutability: 'view',
    inputs: [{ name: 'member', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'memberDeposit',
    stateMutability: 'view',
    inputs: [{ name: 'member', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'claimableYield',
    stateMutability: 'view',
    inputs: [{ name: 'member', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'periodInfo',
    stateMutability: 'view',
    inputs: [
      { name: 'cycleId', type: 'uint256' },
      { name: 'periodId', type: 'uint256' },
    ],
    outputs: [
      { name: 'status', type: 'uint8' },
      { name: 'startAt', type: 'uint64' },
      { name: 'contributionDeadline', type: 'uint64' },
      { name: 'auctionDeadline', type: 'uint64' },
      { name: 'recipient', type: 'address' },
      { name: 'bestBidder', type: 'address' },
      { name: 'bestDiscount', type: 'uint256' },
      { name: 'totalContributed', type: 'uint256' },
      { name: 'payoutAmount', type: 'uint256' },
      { name: 'payoutClaimed', type: 'bool' },
      { name: 'reputationSnapshotId', type: 'bytes32' },
    ],
  },
  {
    type: 'function',
    name: 'runtimeStatus',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      {
        name: 'status',
        type: 'tuple',
        components: [
          { name: 'poolStatus', type: 'uint8' },
          { name: 'currentCycle', type: 'uint256' },
          { name: 'currentPeriod', type: 'uint256' },
          { name: 'storedPeriodStatus', type: 'uint8' },
          { name: 'syncAction', type: 'uint8' },
          { name: 'startAt', type: 'uint64' },
          { name: 'contributionDeadline', type: 'uint64' },
          { name: 'auctionDeadline', type: 'uint64' },
          { name: 'payoutDeadline', type: 'uint64' },
          { name: 'cycleCompleted', type: 'bool' },
          { name: 'extendVoteOpen', type: 'bool' },
          { name: 'extendVoteDeadline', type: 'uint64' },
          { name: 'allActiveContributed', type: 'bool' },
          { name: 'projectedRecipient', type: 'address' },
          { name: 'projectedDiscount', type: 'uint256' },
          { name: 'projectedPayoutAmount', type: 'uint256' },
          { name: 'unpaidActiveMembers', type: 'address[]' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'inviteProposal',
    stateMutability: 'view',
    inputs: [{ name: 'proposalId', type: 'uint256' }],
    outputs: [
      { name: 'candidate', type: 'address' },
      { name: 'yesVotes', type: 'uint256' },
      { name: 'noVotes', type: 'uint256' },
      { name: 'open', type: 'bool' },
    ],
  },
  {
    type: 'function',
    name: 'joinRequest',
    stateMutability: 'view',
    inputs: [{ name: 'requestId', type: 'uint256' }],
    outputs: [
      { name: 'applicant', type: 'address' },
      { name: 'yesVotes', type: 'uint256' },
      { name: 'noVotes', type: 'uint256' },
      { name: 'open', type: 'bool' },
    ],
  },
  {
    type: 'function',
    name: 'proposeInvite',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'candidate', type: 'address' }],
    outputs: [{ name: 'proposalId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'voteInvite',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'proposalId', type: 'uint256' },
      { name: 'support', type: 'bool' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'acceptInvite',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'proposalId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'submitJoinRequest',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [{ name: 'requestId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'voteJoinRequest',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'requestId', type: 'uint256' },
      { name: 'support', type: 'bool' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'acceptJoinRequest',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'requestId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'cancelJoinRequest',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'requestId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'contribute',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'submitDiscountBid',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'discount', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'syncRuntime',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'claimPayout',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'claimYield',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'markDefaultAndArchive',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'defaultedMember', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'voteExtendCycle',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'support', type: 'bool' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'archive',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'leaveDuringForming',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'leaveAfterArchive',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
] as const;

export const ERC20_ABI = [
  {
    type: 'function',
    name: 'approve',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'allowance',
    stateMutability: 'view',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'spender', type: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
] as const;
